# Generated by Django 5.1 on 2024-08-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_name_remove_table2_user_profile_useraccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.name'),
        ),
    ]
